config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  
  get 'top/main'
  post 'top/login'
  get 'top/logout'
  
  root 'top#main'
  
  resources :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        user = User.find_by(uid: session[:login_uid])
        user.like_tweets << tweet
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        user = User.find_by(uid: session[:login_uid])
        tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid]
            redirect_to tweets_path
        else
            render "login"
        end
    end
    
    def login
        user = User.find_by(uid: params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to top_main_path
        else
            render "error", status: 422
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    t = Tweet.new(message: params[:tweet][:message])
    t.user = User.find_by(uid: session[:login_uid])
    t.save
    redirect_to tweets_path
  end
  
  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to tweets_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    signup_password = BCrypt::Password.create(params[:user][:pass])
    u = User.new(uid: params[:user][:uid], pass: signup_password)
    u.save
    redirect_to users_path
  end
  
  def destroy
    User.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L5</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ユーザーIDかパスワードが違います。

app/views/top/login.html.erb
<%= form_with url: '/top/login', method: :post, local: true do |f| %>
    <%= f.label :uid, 'ユーザーID' %>
    <%= f.text_field :uid %>
    <%= f.label :pass, 'パスワード' %>
    <%= f.password_field :pass %>
    <%= f.submit 'ログイン' %>
<% end %>

<%= link_to 'ユーザー登録', new_user_path %>

<%= link_to 'ユーザー一覧', users_path %>

app/views/tweets/index.html.erb
<% @tweets.each do |e| %>
  <%= e.message %>
  (<%= e.user_id %>)
  <%= link_to '削除', tweet_path(e), data: { turbo_method: :delete } %>
  <%= link_to 'いいね', likes_path(tweet_id: e.id), data: { turbo_method: :post } %>
  <%= link_to 'いいね削除', like_path(e), data: { turbo_method: :delete } %>
  <%= e.like_users.include?(User.find_by(uid:session[:login_uid])) %>
  <br>
<% end %>

<%= link_to "新規追加", new_tweet_path %>

<%= link_to "ログアウト",   top_logout_path %>

app/views/tweets/new.html.erb
<%= form_with model: @tweet do |f| %>
  <%= f.label :message, 'message' %>
  <%= f.text_field :message %>
  <%= f.submit 'ツイート' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |e| %>
  uid: <%= e.uid %>, pass: <%= e.pass %>
  <%= link_to '削除', user_path(e), data: {turbo_method: :delete } %>
  <br>
<% end %>

<%= link_to '新規追加', new_user_path %>

<%= link_to "ログイン", root_path %>

<!-- def create
#   t= Tweet.new(message: params[:tweet][:message])
#   t.user = User.first
#   t.save
#   redirect_to 
-->

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
  <%= f.label :uid, 'UID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'PASS' %>
  <%= f.text_field :pass %>
  <%= f.submit '登録' %>
<% end %>